# Generated by Django 4.0 on 2023-03-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_imagem_remove_projeto_imagem_projeto_imagens'),
    ]

    operations = [
    ]
