# Generated by Django 4.0 on 2023-03-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20230307_1437'),
    ]

    operations = [
    ]
