# Generated by Django 4.0 on 2023-03-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20230307_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'default_related_name': 'imagens', 'verbose_name_plural': 'imagens'},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagens',
        ),
        migrations.AddField(
            model_name='imagem',
            name='projeto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
