# Generated by Django 4.0 on 2023-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_imagem_options_remove_projeto_imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='descricao',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
