# Generated by Django 4.0 on 2023-03-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_imagem_descricao'),
    ]

    operations = [
    ]
