# Generated by Django 4.0 on 2023-03-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20230307_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='video_link',
        ),
        migrations.AddField(
            model_name='imagem',
            name='tumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagens',
            field=models.ManyToManyField(related_name='projeto_imagens', to='portfolio.Imagem'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_thumbnail', to='portfolio.imagem'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='video_youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='projeto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto'),
        ),
    ]
