# Generated by Django 4.0 on 2023-03-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_imagem_options_remove_imagem_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='tumbnail',
        ),
        migrations.AddField(
            model_name='imagem',
            name='thumbnail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagens',
            field=models.ManyToManyField(blank=True, related_name='projeto_imagens', to='portfolio.Imagem'),
        ),
    ]
