# Generated by Django 4.0 on 2023-03-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_imagem_tumbnail_imagem_thumbnail_and_more'),
    ]

    operations = [
    ]
