# Generated by Django 4.0 on 2023-03-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_imagem_thumbnail_remove_projeto_imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='projeto',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto'),
        ),
    ]
