# Generated by Django 4.0 on 2023-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_projeto_link_youtube_alter_imagem_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.TextField(blank=True, default=''),
        ),
    ]
